version: v2.0

name: build

on:
  push:
    - main
  mr:
    - main

stages:
  - name: scan and release
    jobs:
      scan:
        name: scan
        steps:
          - checkout: self
          - uses: CodeccCheckAtomDebug@4.*
            name: 腾讯代码分析
            with:
              languages:
                - PYTHON
              checkerSetType: openScan
              rtxReceiverType: 4
              emailReceiverType: 4
      build:
        name: update pypi mirror
        steps:
          - checkout: self
          - run: python setup.py sdist
          - run: pip install twine
          - run: twine upload dist/*.tar.gz --repository-url https://mirrors.tencent.com/repository/pypi/tencent_pypi/simple --username ${{settings.pypi.username}} --password ${{settings.pypi.password}}

notices:
  - type: wework-message
    if: FAILURE